export enum CertificateStatus {
  VALID = "VALID",
  EXPIRING_SOON = "EXPIRING_SOON",
  CRITICAL = "CRITICAL",
  EXPIRED = "EXPIRED",
  PENDING_RENEWAL = "PENDING_RENEWAL",
  SUSPENDED = "SUSPENDED",
}
