/**
 * @maris/shared — Maritime domain enums
 */

export enum CompanyType {
  SHIP_OWNER = "SHIP_OWNER",
  SHIP_MANAGER = "SHIP_MANAGER",
  CHARTERER = "CHARTERER",
  HOLDING = "HOLDING",
}

export enum VesselType {
  BULK_CARRIER = "BULK_CARRIER",
  TANKER_CRUDE = "TANKER_CRUDE",
  TANKER_PRODUCT = "TANKER_PRODUCT",
  TANKER_CHEMICAL = "TANKER_CHEMICAL",
  CONTAINER = "CONTAINER",
  GENERAL_CARGO = "GENERAL_CARGO",
  RO_RO = "RO_RO",
  PASSENGER = "PASSENGER",
  OFFSHORE_SUPPLY = "OFFSHORE_SUPPLY",
  TUGBOAT = "TUGBOAT",
  BARGE = "BARGE",
  LNG_CARRIER = "LNG_CARRIER",
  OTHER = "OTHER",
}

export enum VesselStatus {
  ACTIVE = "ACTIVE",
  DRYDOCK = "DRYDOCK",
  LAID_UP = "LAID_UP",
  SCRAPPED = "SCRAPPED",
  SOLD = "SOLD",
}

export enum FuelType {
  HFO = "HFO",
  MDO = "MDO",
  MGO = "MGO",
  LNG = "LNG",
  LPG = "LPG",
  METHANOL = "METHANOL",
}

export enum CrewRank {
  MASTER = "MASTER",
  CHIEF_OFFICER = "CHIEF_OFFICER",
  SECOND_OFFICER = "SECOND_OFFICER",
  THIRD_OFFICER = "THIRD_OFFICER",
  CHIEF_ENGINEER = "CHIEF_ENGINEER",
  SECOND_ENGINEER = "SECOND_ENGINEER",
  THIRD_ENGINEER = "THIRD_ENGINEER",
  FOURTH_ENGINEER = "FOURTH_ENGINEER",
  BOSUN = "BOSUN",
  ABLE_SEAMAN = "ABLE_SEAMAN",
  ORDINARY_SEAMAN = "ORDINARY_SEAMAN",
  FITTER = "FITTER",
  OILER = "OILER",
  WIPER = "WIPER",
  CHIEF_COOK = "CHIEF_COOK",
  MESSMAN = "MESSMAN",
  ELECTRICIAN = "ELECTRICIAN",
  RADIO_OFFICER = "RADIO_OFFICER",
}

export enum SeafarerStatus {
  ACTIVE = "ACTIVE",
  ON_LEAVE = "ON_LEAVE",
  RESIGNED = "RESIGNED",
  BLACKLISTED = "BLACKLISTED",
}

export enum ContractStatus {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  TERMINATED = "TERMINATED",
}

export enum CertificateStatus {
  VALID = "VALID",
  EXPIRING_SOON = "EXPIRING_SOON",
  CRITICAL = "CRITICAL",
  EXPIRED = "EXPIRED",
  PENDING_RENEWAL = "PENDING_RENEWAL",
  SUSPENDED = "SUSPENDED",
}

export enum VoyageStatus {
  PLANNED = "PLANNED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum JobStatus {
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum PermissionScope {
  OWN = "OWN",
  COMPANY = "COMPANY",
  ALL = "ALL",
}

export enum AuditAction {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  RESTORE = "RESTORE",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  EXPORT = "EXPORT",
  IMPORT = "IMPORT",
  APPROVE = "APPROVE",
  REJECT = "REJECT",
}
