/* eslint-disable no-console */
import { PrismaClient, Company, Vessel, VesselType, VesselStatus, FuelType } from "@prisma/client";
import { Prisma } from "@prisma/client";

export async function seedVessels(
  prisma: PrismaClient,
  companies: Record<string, Company>,
): Promise<Record<string, Vessel>> {
  console.log("Seeding vessels...");

  const vesselsData = [
    // NJM Vessels
    {
      companyCode: "NJM",
      name: "MV Nusantara Jaya 1",
      imoNumber: "9100001",
      mmsiNumber: "525000001",
      callSign: "YDA3001",
      flagState: "ID",
      portOfRegistry: "Tanjung Priok",
      vesselType: "BULK_CARRIER" as VesselType,
      status: "ACTIVE" as VesselStatus,
      grossTonnage: new Prisma.Decimal(25000),
      netTonnage: new Prisma.Decimal(15000),
      deadweightTonnage: new Prisma.Decimal(40000),
      lengthOverall: new Prisma.Decimal(189.9),
      breadth: new Prisma.Decimal(32.2),
      depth: new Prisma.Decimal(16.5),
      yearBuilt: 2012,
      shipyard: "Palindo Marine",
      shipyardCountry: "Indonesia",
      classSociety: "BKI",
      classNumber: "BKI-12345",
      mainEngineType: "Wartsila 6RT-flex50-D",
      mainEnginePower: new Prisma.Decimal(9960),
      fuelType: "HFO" as FuelType,
    },
    {
      companyCode: "NJM",
      name: "MV Nusantara Jaya 2",
      imoNumber: "9100002",
      mmsiNumber: "525000002",
      callSign: "YDA3002",
      flagState: "ID",
      portOfRegistry: "Surabaya",
      vesselType: "TANKER_PRODUCT" as VesselType,
      status: "ACTIVE" as VesselStatus,
      grossTonnage: new Prisma.Decimal(18000),
      netTonnage: new Prisma.Decimal(11000),
      deadweightTonnage: new Prisma.Decimal(30000),
      lengthOverall: new Prisma.Decimal(172.0),
      breadth: new Prisma.Decimal(28.0),
      depth: new Prisma.Decimal(14.8),
      yearBuilt: 2015,
      shipyard: "Dumas Tanjung Perak Shipyard",
      shipyardCountry: "Indonesia",
      classSociety: "BKI",
      classNumber: "BKI-12346",
      mainEngineType: "MAN B&W 6S42MC",
      mainEnginePower: new Prisma.Decimal(6480),
      fuelType: "MDO" as FuelType,
    },
    {
      companyCode: "NJM",
      name: "MV Nusantara Jaya 3",
      imoNumber: "9100003",
      mmsiNumber: "525000003",
      callSign: "YDA3003",
      flagState: "ID",
      portOfRegistry: "Belawan",
      vesselType: "GENERAL_CARGO" as VesselType,
      status: "DRYDOCK" as VesselStatus,
      grossTonnage: new Prisma.Decimal(8500),
      netTonnage: new Prisma.Decimal(4500),
      deadweightTonnage: new Prisma.Decimal(12000),
      lengthOverall: new Prisma.Decimal(125.5),
      breadth: new Prisma.Decimal(20.0),
      depth: new Prisma.Decimal(10.5),
      yearBuilt: 2008,
      shipyard: "Adiluhung Saranasegara",
      shipyardCountry: "Indonesia",
      classSociety: "BKI",
      classNumber: "BKI-12347",
      mainEngineType: "Hanshin LH46LA",
      mainEnginePower: new Prisma.Decimal(3300),
      fuelType: "MGO" as FuelType,
    },
    // ASL Vessels
    {
      companyCode: "ASL",
      name: "MV Sentosa Star",
      imoNumber: "9200001",
      mmsiNumber: "563000001",
      callSign: "9V3001",
      flagState: "SG",
      portOfRegistry: "Singapore",
      vesselType: "CONTAINER" as VesselType,
      status: "ACTIVE" as VesselStatus,
      grossTonnage: new Prisma.Decimal(35000),
      netTonnage: new Prisma.Decimal(21000),
      deadweightTonnage: new Prisma.Decimal(45000),
      lengthOverall: new Prisma.Decimal(220.0),
      breadth: new Prisma.Decimal(32.2),
      depth: new Prisma.Decimal(19.0),
      yearBuilt: 2018,
      shipyard: "Imabari Shipbuilding",
      shipyardCountry: "Japan",
      classSociety: "DNV",
      classNumber: "DNV-54321",
      mainEngineType: "MAN B&W 7S70MC-C",
      mainEnginePower: new Prisma.Decimal(21770),
      fuelType: "HFO" as FuelType,
    },
    {
      companyCode: "ASL",
      name: "MV Sentosa Pearl",
      imoNumber: "9200002",
      mmsiNumber: "354000001",
      callSign: "HP3001",
      flagState: "PA",
      portOfRegistry: "Panama",
      vesselType: "BULK_CARRIER" as VesselType,
      status: "LAID_UP" as VesselStatus,
      grossTonnage: new Prisma.Decimal(45000),
      netTonnage: new Prisma.Decimal(27000),
      deadweightTonnage: new Prisma.Decimal(82000),
      lengthOverall: new Prisma.Decimal(229.0),
      breadth: new Prisma.Decimal(32.25),
      depth: new Prisma.Decimal(20.0),
      yearBuilt: 2020,
      shipyard: "Oshima Shipbuilding",
      shipyardCountry: "Japan",
      classSociety: "Lloyd's",
      classNumber: "LR-98765",
      mainEngineType: "MAN B&W 6G50ME-C9",
      mainEnginePower: new Prisma.Decimal(8430),
      fuelType: "LNG" as FuelType,
    },
  ];

  const seededVessels: Record<string, Vessel> = {};

  for (const data of vesselsData) {
    const company = companies[data.companyCode];
    if (!company) {
      console.warn(`  ⚠️ Company ${data.companyCode} not found for vessel ${data.name}. Skipping.`);
      continue;
    }

    const vessel = await prisma.vessel.upsert({
      where: { imoNumber: data.imoNumber },
      update: {
        name: data.name,
        companyId: company.id,
        mmsiNumber: data.mmsiNumber,
        callSign: data.callSign,
        flagState: data.flagState,
        portOfRegistry: data.portOfRegistry,
        vesselType: data.vesselType,
        status: data.status,
        grossTonnage: data.grossTonnage,
        netTonnage: data.netTonnage,
        deadweightTonnage: data.deadweightTonnage,
        lengthOverall: data.lengthOverall,
        breadth: data.breadth,
        depth: data.depth,
        yearBuilt: data.yearBuilt,
        shipyard: data.shipyard,
        shipyardCountry: data.shipyardCountry,
        classSociety: data.classSociety,
        classNumber: data.classNumber,
        mainEngineType: data.mainEngineType,
        mainEnginePower: data.mainEnginePower,
        fuelType: data.fuelType,
        updatedBy: "SEED",
      },
      create: {
        name: data.name,
        companyId: company.id,
        imoNumber: data.imoNumber,
        mmsiNumber: data.mmsiNumber,
        callSign: data.callSign,
        flagState: data.flagState,
        portOfRegistry: data.portOfRegistry,
        vesselType: data.vesselType,
        status: data.status,
        grossTonnage: data.grossTonnage,
        netTonnage: data.netTonnage,
        deadweightTonnage: data.deadweightTonnage,
        lengthOverall: data.lengthOverall,
        breadth: data.breadth,
        depth: data.depth,
        yearBuilt: data.yearBuilt,
        shipyard: data.shipyard,
        shipyardCountry: data.shipyardCountry,
        classSociety: data.classSociety,
        classNumber: data.classNumber,
        mainEngineType: data.mainEngineType,
        mainEnginePower: data.mainEnginePower,
        fuelType: data.fuelType,
        createdBy: "SEED",
        updatedBy: "SEED",
      },
    });

    seededVessels[data.imoNumber] = vessel;
    console.log(`  - Vessel ${vessel.name} (IMO: ${vessel.imoNumber}, Type: ${vessel.vesselType})`);
  }

  console.log("  ✅ Seeded vessels.");
  return seededVessels;
}
